export const SEARCH = "SEARCH";
export const ROBOTS_FETCH_PENDING = "ROBOTS_FETCH_PENDING";
export const ROBOTS_FETCH_SUCCESS = "ROBOTS_FETCH_SUCCESS";
export const ROBOTS_FETCH_ERROR = "ROBOTS_FETCH_ERROR";
